story_list = {"An Unearthly Child",
"The Daleks",
"The Edge of Destruction", 
              "Marco Polo", 
              "The Keys of Marinus", 
              "The Aztecs", 
              "The Sensorites", 
              "The Reign of Terror", 
              "Planet of Giants", 
              "The Dalek Invasion of Earth", 
              "The Rescue", 
              "The Romans", 
              "The Web Planet", 
              "The Crusade", 
              "The Space Museum", 
              "The Chase", 
              "The Time Meddler", 
              "Galaxy 4", 
              "Mission to the Unknown", 
              "The Myth Makers", 
              "The Daleks' Master Plan", 
              "The Massacre of St Bartholemew's Eve", 
              "The Ark", 
              "The Celestial Toymaker", 
              "The Gunfighters", 
              "The Savages", 
              "The War Machines", 
              "The Smugglers", 
              "The Tenth Planet", 
              "The Power of the Daleks", 
              "The Highlanders", 
              "The Underwater Menace", 
              "The Moonbase", 
              "The Macra Terror", 
              "The Faceless Ones", 
              "The Evil of the Daleks", 
              "The Tomb of the Cybermen", 
              "The Abominable Snowmen", 
              "The Ice Warriors", 
              "The Enemy of the World", 
              "The Web of Fear", 
              "Fury from the Deep", 
              "The Wheel in Space", 
              "The Dominators", 
              "The Mind Robber", 
              "The Invasion", 
              "The Krotons", 
              "The Seeds of Death", 
              "The Space Pirates", 
              "The War Games", 
              "Spearhead from Space", 
              "Doctor Who and the Silurians", 
              "The Ambassadors of Death", 
              "Inferno", 
              "Terror of the Autons", 
              "The Mind of Evil", 
              "The Claws of Axos", 
              "Colony in Space", 
              "The Daemons", 
              "Day of the Daleks", 
              "The Curse of Peladon", 
              "The Sea Devils", 
              "The Mutants", 
              "The Time Monster", 
              "The Three Doctors", 
              "Carnival of Monsters", 
              "Frontier in Space", 
              "Planet of the Daleks", 
              "The Green Death", 
              "The Time Warrior", 
              "Invasion of the Dinosaurs", 
              "Death to the Daleks", 
              "The Monster of Peladon", 
              "Planet of the Spiders", 
              "Robot", 
              "The Ark in Space", 
              "The Sontaran Experiment", 
              "Genesis of the Daleks", 
              "Revenge of the Cybermen", 
              "Terror of the Zygons", 
              "Planet of Evil", 
              "Pyramids of Mars", 
              "The Android Invasion", 
              "The Brain of Morbius", 
              "The Seeds of Doom", 
              "The Masque of Mandragora", 
              "The Hand of Fear", 
              "The Deadly Assassin", 
              "The Face of Evil", 
              "The Robots of Death", 
              "The Talons of Weng-Chiang", 
              "Horror of Fang Rock", 
              "The Invisible Enemy", 
              "Image of the Fendahl", 
              "The Sun Makers", 
              "Underworld", 
              "The Invasion of Time", 
              "The Ribos Operation", 
              "The Pirate Planet", 
              "The Stones of Blood", 
              "The Androids of Tara", 
              "The Power of Kroll", 
              "The Armageddon Factor", 
              "Destiny of the Daleks", 
              "City of Death", 
              "The Creature from the Pit", 
              "Nightmare of Eden", 
              "The Horns of Nimon", 
              "The Leisure Hive", 
              "Meglos", 
              "Full Circle", 
              "State of Decay", 
              "Warriors' Gate", 
              "The Keeper of Traken", 
              "Logopolis", 
              "Castrovalva", 
              "Four to Doomsday", 
              "Kinda", 
              "The Visitation", 
              "Black Orchid", 
              "Earthshock", 
              "Time-Flight", 
              "Arc of Infinity", 
              "Snakedance", 
              "Mawdryn Undead", 
              "Terminus", 
              "Enlightenment", 
              "The King's Demons", 
              "The Five Doctors", 
              "Warriors of the Deep", 
              "The Awakening", 
              "Frontios", 
              "Resurrection of the Daleks", 
              "Planet of Fire", 
              "The Caves of Androzani", 
              "The Twin Dilemma", 
              "Attack of the Cybermen", 
              "Vengeance on Varos", 
              "The Mark of the Rani", 
              "The Two Doctors", 
              "Timelash", 
              "Revelation of the Daleks", 
              "The Mysterious Planet", 
              "Mindwarp", 
              "Terror of the Vervoids", 
              "The Ultimate Foe", 
              "Time and the Rani", 
              "Paradise Towers", 
              "Delta and the Bannermen", 
              "Dragonfire", 
              "Remembrance of the Daleks", 
              "The Happiness Patrol", 
              "Silver Nemesis", 
              "The Greatest Show in the Galaxy", 
              "Battlefield", 
              "Ghost Light", 
              "The Curse of Fenric", 
              "Survival", 
              "Doctor Who The Movie", 
              "Rose", 
              "The End of the World", 
              "The Unquiet Dead", 
              "Aliens of London/World War Three", 
              "Dalek", 
              "The Long Game", 
              "Father's Day", 
              "The Empty Child/The Doctor Dances", 
              "Boom Town", 
              "Bad Wolf/The Parting of the Ways", 
              "The Christmas Invasion", 
              "New Earth", 
              "Tooth and Claw", 
              "School Reunion", 
              "The Girl in the Fireplace", 
              "Rise of the Cybermen/The Age of Steel", 
              "The Idiot's Lantern", 
              "The Impossible Planet/The Satan Pit", 
              "Love & Monsters", 
              "Fear Her", 
              "Army of Ghosts/Doomsday", 
              "The Runaway Bride", 
              "Smith and Jones", 
              "The Shakespeare Code", 
              "Gridlock", 
              "Daleks in Manhattan/Evolution of the Daleks", 
              "The Lazarus Experiment", 
              "42", 
              "Human Nature/The Family of Blood", 
              "Blink", 
              "Utopia", 
              "The Sound of Drums/Last of the Time Lords", 
              "Time Crash", 
              "Voyage of the Damned", 
              "Partners in Crime", 
              "The Fires of Pompeii", 
              "Planet of the Ood", 
              "The Sontaran Stratagem/The Poison Sky", 
              "The Doctor's Daughter", 
              "The Unicorn and the Wasp", 
              "Silence in the Library/Forest of the Dead", 
              "Midnight", 
              "Turn Left", 
              "The Stolen Earth/Journey's End", 
              "The Next Doctor", 
              "Planet of the Dead", 
              "The Waters of Mars", 
              "The End of Time", 
              "The Eleventh Hour", 
              "The Beast Below", 
              "Victory of the Daleks", 
              "The Time of Angels/Flesh and Stone", 
              "The Vampires of Venice", 
              "Amy's Choice", 
              "The Hungry Earth/Cold Blood", 
              "Vincent and the Doctor", 
              "The Lodger", 
              "The Pandorica Opens/The Big Bang", 
              "A Christmas Carol", 
              "The Impossible Astronaut/Day of the Moon", 
              "The Curse of the Black Spot", 
              "The Doctor's Wife", 
              "The Rebel Flesh/The Almost People", 
              "A Good Man Goes to War", 
              "Let's Kill Hitler", 
              "Night Terrors", 
              "The Girl Who Waited", 
              "The God Complex", 
              "Closing Time", 
              "The Wedding of River Song", 
              "The Doctor The Widow and The Wardrobe", 
              "Asylum of the Daleks", 
              "Dinosaurs On A Spaceship", 
              "A Town Called Mercy", 
              "The Power Of Three", 
              "The Angels Take Manhattan", 
              "The Snowmen", 
              "The Bells of Saint John", 
              "The Rings Of Akhaten", 
              "Cold War", 
              "Hide", 
              "Journey to the Centre of the TARDIS", 
              "The Crimson Horror", 
              "Nightmare in Silver", 
              "The Name of the Doctor", 
              "The Day of the Doctor", 
              "The Time of the Doctor", 
              "Deep Breath", 
              "Into The Dalek", 
              "Robot Of Sherwood", 
              "Listen", 
              "Time Heist", 
              "The Caretaker", 
              "Kill the Moon", 
              "Mummy on the Orient Express", 
              "Flatline", 
              "In the Forest of the Night", 
              "Dark Water/Death in Heaven", 
              "Last Christmas", 
              "The Magician’s Apprentice/The Witch’s Familiar", 
              "Under The Lake/Before The Flood", 
              "The Girl Who Died", 
              "The Woman Who Lived", 
              "The Zygon Invasion/The Zygon Inversion", 
              "Sleep No More", 
              "Face The Raven", 
              "Heaven Sent", 
              "Hell Bent", 
              "The Husbands of River Song", 
              "The Return of Doctor Mysterio", 
              "The Pilot", 
              "Smile", 
              "Thin Ice", 
              "Knock Knock", 
              "Oxygen", 
              "Extremis", 
              "The Pyramid at the End of the World", 
              "The Lie of the Land", 
              "Empress of Mars", 
              "The Eaters of Light", 
              "World Enough and Time/The Doctor Falls", 
              "Twice Upon a Time", 
              "The Woman Who Fell to Earth", 
              "The Ghost Monument", 
              "Rosa", 
"Arachnids in the UK", 
"The Tsuranga Conundrum", 
"Demons of the Punjab", 
"Kerblam!", 
"The Witchfinders", 
"It Takes You Away", 
"The Battle of Ranskoor Av Kolos", 
"Resolution", 
"Spyfall", 
"Orphan 55", 
"Nikola Tesla’s Night of Terror", 
"Fugitive of the Judoon", 
"Praxeus", 
"Can You Hear Me?", 
"The Haunting of Villa Diodati", 
"Ascension of the Cybermen/The Timeless Children", 
"Revolution of the Daleks", 
"The Halloween Apocalypse", 
"War of the Sontarans", 
"Once, Upon Time", 
"Village of the Angels", 
"Survivors of the Flux", 
"The Vanquishers", 
"Eve of the Daleks", 
"Legend of the Sea Devils", 
"The Power of the Doctor", 
"The Star Beast", 
"Blue Wild Yonder", 
"The Giggle", 
"The Church on Ruby Road", 
"The Devil's Chord", 
"Space Babies", 
"Boom", 
"73 Yards", 
"Dot and Bubble", 
"Rogue", 
              "The Legend of Ruby Sunday/Empire of Death", 
              "The Robot Revolution", 
              "Lux", 
              "The Well", 
              "Lucky Day", 
              "The Story and the Engine", 
              "Wish World/The Reality War"
}
